const codePromo = require('./codePromo.route')
const addPoint = require('./addPoint.route')
const getTokenBO = require('./getTokenBO.route')
const account = require('./account.route')
const randomCode = require('./randomCode.route')
const checkAuth = require('./checkAuth.route')
const getMemberBO = require('./getMemberBO.route')
const findMemo = require('./findMemo.route')
const deposit = require('./depositToken.router')
const getTimeZone = require('./getTimeZone.route')
const changePass = require('./changePass.router')
const ipfp = require('./ipfp.route')

module.exports = (app) => {{
    app.use('/api/code', codePromo)
    app.use('/api/add-point', addPoint)
    app.use('/api/get-token-bo', getTokenBO)
    app.use('/api/account', account)
    app.use('/api/generate-code', randomCode)
    app.use('/api/checkAuth', checkAuth)
    app.use('/api/getMemberBO', getMemberBO)
    app.use('/api/find-memo', findMemo)
    app.use('/api/deposit', deposit)
    app.use('/api/get-time-zone', getTimeZone)
    app.use('/api/change-pass', changePass)
    app.use('/api/ipfp', ipfp)
}}